### ISSUE TITLE
Is it possible to create a =let* implementation?

### ISSUE THREAD

**Issue by NicholasBHubbard** [eugeneia/maxpc#13]
It would be useful to be able to bind intermediate parse values to variables that can be used as inputs to subsequent parsers. I have spent the last few days trying to come up with an implementation of `=let*` from mpc (or `.let*` from smug) in maxpc but I can't get anything to work. I understand that both `=let*` and `.let*` are defined in terms of the monadic bind function, but I am wondering if it would be possible to hack together a macro for maxpc that has the same semantics.

I would like to contribute a `=let*` implementation but unfortunately I have hit a wall here on my own.

**Comment by eugeneia** [comment]
Something like this?

```lisp
 (use-package '(:maxpc :maxpc.char))

(defun %bind (parser make-parser)
  (lambda (input)
    (multiple-value-bind (rest value) (funcall parser input)
      (when rest
        (funcall (funcall make-parser value) rest)))))

;; Parses foobar and barfoo but not barbar
(parse "foobar"
       (%bind (=subseq (%or (?string "foo")
                            (?string "bar")))
              (lambda (prefix)
                (if (string= prefix "foo")
                    (?string "bar")
                    (?string "foo")))))
```

I didn’t provide a bind primitive because it seemed overly powerful to me. Maybe you need it for parsing context-sensitive languages? I never needed to.

Anyhow I think it should be possible to extend maxpc with `%bind` in your project and derive a `let*` macro from that.

**Comment by eugeneia** [comment]
I suppose a `let` macro would have a structure like this:

```lisp
(defmacro %let1 (name value &body body)
  `(%bind ,value
          (lambda (,name)
            ,@body)))
```

**Comment by NicholasBHubbard** [comment]
Thanks! If this is something you would accept into maxpc I would be happy to submit a PR with %bind, %let1, and a %let*, including documentation.

**Comment by NicholasBHubbard** [comment]
Seems like this works.
```
(defun %bind (parser make-parser)
  (lambda (input)
    (multiple-value-bind (rest value) (funcall parser input)
      (when rest
        (funcall (funcall make-parser value) rest)))))

(defmacro %let* (bindings &body body)
  (if (null bindings)
      (let ((input (gensym "input")))
        `(lambda (,input) (values ,input (progn ,@body))))
      (let ((var (first (first bindings)))
            (parser (second (first bindings))))
        `(%bind ,parser
                (lambda (,var)
                  ,(when (string= var "_")
                     `(declare (ignore ,var)))
                  (%let* ,(rest bindings) ,@body))))))

(defun =foo ()
  (%let* ((foo1 (=subseq (?string "foo")))
          (_ (?whitespace))
          (foo2 (=subseq (?string foo1)))
          (_ (?whitespace))
          (bar (=subseq (?string "bar"))))
    (concatenate 'string foo1 foo2 bar)))

PARSER> (parse "foo foo bar" (=foo))
"foofoobar"
T
T
```

**Comment by eugeneia** [comment]
Cool! Mind to carry this code around as an extension in your project for now? I can’t really tell right now if this is a commonly needed feature that should be ubiquitous, or something niche. If this keeps popping up as a feature request then I’d point towards you and suggest merging something based on the state-of-the-art version you ended up using. :-)

**Comment by NicholasBHubbard** [comment]
Sounds good

**Comment by NicholasBHubbard** [comment]
I wrote an extension library for MaxPC that includes a `%let*` implementation.

https://github.com/NicholasBHubbard/maxpc-extensions
